import type { Metadata } from "next";
import Homebanner from "./components/Homepage/Homebanner";
import Navbar from "@/components/Navbar";
// import MainComponent from "./components/dashboard/MainComponent";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="h-[calc(100vh-28px)]">
      <Navbar variant="primary" />
      <Homebanner />
    </div>
  );
}
