import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="h-[calc(100vh-28px)]">
      
    </div>
  );
}
