import React from "react";
import type { Metadata } from "next";
import MainComponent from "../components/dashboard/MainComponent";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const Dashboard = () => {
  return (
    <div className="!bg-[#0B0E13]">
      <MainComponent />
    </div>
  );
};

export default Dashboard;
